const main = async () => {
  console.log("Starting relay...");
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
